pools:
  default_redis:
    type: redis
    settings:
      host: localhost
      port: 6379
      db: 1
      decode_responses: true
adapters:
  RedisKVAdapter:
    class_name: RedisKVAdapter
    use_pool: default_redis
