name: WestWorldEnvironment
components:
  relation:
    plugin:
      BasicRelationPlugin:
        adapters: {}
        relations: "agents_relation"
  overseer:
    plugin:
      OverseerPlugin:
        adapters: {}
  scene_sweetwater_saloon:
    plugin:
      Scene_sweetwater_saloon_Plugin:
        adapters: {}
        location_id: sweetwater_saloon
  scene_abernathy_ranch:
    plugin:
      Scene_abernathy_ranch_Plugin:
        adapters: {}
        location_id: abernathy_ranch
  scene_sweetwater:
    plugin:
      Scene_sweetwater_Plugin:
        adapters: {}
        location_id: sweetwater
  scene_sweetwater_plaza:
    plugin:
      Scene_sweetwater_plaza_Plugin:
        adapters: {}
        location_id: sweetwater_plaza
  scene_sweetwater_sheriff:
    plugin:
      Scene_sweetwater_sheriff_Plugin:
        adapters: {}
        location_id: sweetwater_sheriff
  scene_sweetwater_post_office:
    plugin:
      Scene_sweetwater_post_office_Plugin:
        adapters: {}
        location_id: sweetwater_post_office
  scene_sweetwater_train_station:
    plugin:
      Scene_sweetwater_train_station_Plugin:
        adapters: {}
        location_id: sweetwater_train_station
  scene_sweetwater_hotel:
    plugin:
      Scene_sweetwater_hotel_Plugin:
        adapters: {}
        location_id: sweetwater_hotel
  scene_sweetwater_hospital:
    plugin:
      Scene_sweetwater_hospital_Plugin:
        adapters: {}
        location_id: sweetwater_hospital
  scene_sweetwater_gunsmith:
    plugin:
      Scene_sweetwater_gunsmith_Plugin:
        adapters: {}
        location_id: sweetwater_gunsmith
  scene_sweetwater_tailor:
    plugin:
      Scene_sweetwater_tailor_Plugin:
        adapters: {}
        location_id: sweetwater_tailor
  scene_sweetwater_general_store:
    plugin:
      Scene_sweetwater_general_store_Plugin:
        adapters: {}
        location_id: sweetwater_general_store
  scene_wilderness:
    plugin:
      Scene_wilderness_Plugin:
        adapters: {}
        location_id: wilderness
  scene_train:
    plugin:
      Scene_train_Plugin:
        adapters: {}
        location_id: train
  scene_river:
    plugin:
      Scene_river_Plugin:
        adapters: {}
        location_id: river
  scene_mine:
    plugin:
      Scene_mine_Plugin:
        adapters: {}
        location_id: mine
  scene_church:
    plugin:
      Scene_church_Plugin:
        adapters: {}
        location_id: church
  scene_desert_bandit_hideout:
    plugin:
      Scene_desert_bandit_hideout_Plugin:
        adapters: {}
        location_id: desert_bandit_hideout
  scene_pariah:
    plugin:
      Scene_pariah_Plugin:
        adapters: {}
        location_id: pariah
  scene_pariah_casino:
    plugin:
      Scene_pariah_casino_Plugin:
        adapters: {}
        location_id: pariah_casino
  scene_pariah_fight_pit:
    plugin:
      Scene_pariah_fight_pit_Plugin:
        adapters: {}
        location_id: pariah_fight_pit
  scene_frontier_town:
    plugin:
      Scene_frontier_town_Plugin:
        adapters: {}
        location_id: frontier_town
  scene_frontier_outpost:
    plugin:
      Scene_frontier_outpost_Plugin:
        adapters: {}
        location_id: frontier_outpost
  scene_host_room_1:
    plugin:
      Scene_host_room_1_Plugin:
        adapters: {}
        location_id: host_room_1
  scene_host_home_2:
    plugin:
      Scene_host_home_2_Plugin:
        adapters: {}
        location_id: host_home_2
  scene_ranch_farm:
    plugin:
      Scene_ranch_farm_Plugin:
        adapters: {}
        location_id: ranch_farm
  scene_surface_maintenance_station:
    plugin:
      Scene_surface_maintenance_station_Plugin:
        adapters: {}
        location_id: surface_maintenance_station
  scene_backstage_control:
    plugin:
      Scene_backstage_control_Plugin:
        adapters: {}
        location_id: backstage_control
  scene_cold_storage:
    plugin:
      Scene_cold_storage_Plugin:
        adapters: {}
        location_id: cold_storage
  scene_staff_dormitory:
    plugin:
      Scene_staff_dormitory_Plugin:
        adapters: {}
        location_id: staff_dormitory
  scene_programmer_workspace:
    plugin:
      Scene_programmer_workspace_Plugin:
        adapters: {}
        location_id: programmer_workspace
