templates:
  - name: WestWorldStoryHost
    component_order: ["perceive", "plan", "invoke", "state", "reflect"]
    components:
      profile:
        plugin:
          BasicProfilePlugin:
            adapters:
              redis: "RedisKVAdapter"
            profile_data: "agent_profiles"

      state:
        plugin:
          BasicStatePlugin:
            adapters:
              adapter: "RedisKVAdapter"
            state_data: "agent_states"

      perceive:
        plugin:
          WestWorldPerceivePlugin:
            adapters: {}
            locations: "map_locations"

      plan:
        plugin:
          StoryWestWorldPlanPlugin:
            adapters:
              redis: "RedisKVAdapter"
            locations: "map_locations"

      invoke:
        plugin:
          WestWorldInvokePlugin:
            adapters: {}
            locations: "map_locations"

      reflect:
        plugin:
          WestWorldReflectPlugin:
            adapters: {}
