simulation:
  pod_size: 7
  init_batch_size: 7
  max_ticks: 40

configs:
  environment: "../../configs/environment_config.yaml"
  actions: "../../configs/actions_config.yaml"
  agent_templates: "agents_config.yaml"
  system: "../../configs/system_config.yaml"
  database: "db_config.yaml"
  models: "../../configs/models_config.yaml"

data:
  agent_profiles: "data/agents/profiles_sim.jsonl"
  agent_states: "data/agents/states_sim.jsonl"
  agents_relation: "data/relations/relations_sim.jsonl"
  map_locations: "data/map/locations.yaml"
